server:
  port: 8085

logging:
  file:
    path: logs

security:
  jwt:
    secret: ${SPRING_JWT_TOKEN:mZfpLztVGV1ROkxXpXNRwFdoIUuJArRI4k+ouB+Hr4rfydy7hGfMY0+tnXJkmDuMgQkPQ1O6s5VUg5LoepC42g==}
    expiration: ${SPRING_JWT_EXPIRATION:7200000}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: hr_admin               
    password: password                 
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update                      
    show-sql: true                          