server:
  port: 8085

logging:
  file:
    path: logs
    max-size: 1MB
    max-history: 7

security:
  jwt:
    secret: ${SPRING_JWT_TOKEN:mZfpLztVGV1ROkxXpXNRwFdoIUuJArRI4k+ouB+Hr4rfydy7hGfMY0+tnXJkmDuMgQkPQ1O6s5VUg5LoepC42g==}
    expiration: ${SPRING_JWT_EXPIRATION:7200000}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  jackson:
    default-property-inclusion: NON_NULL

