package com.teammanager.util;

public enum Departments {
    HUMAN_RESOURCES,
    FINANCE,
    MARKETING,
    SALES,
    MANAGEMENT,
    IT,
    OPERATIONS,
    LEGAL,
    CUSTOMER_SERVICE,
    ENGINEERING,
    PRODUCT_DEVELOPMENT,
    PROCUREMENT,
    QUALITY_ASSURANCE,
    ADMINISTRATION,
    RESEARCH_AND_DEVELOPMENT,
    TRAINING_AND_DEVELOPMENT,
    PUBLIC_RELATIONS,
    SECURITY,
    LOGISTICS,
    DESIGN,
    HEALTH_AND_SAFETY;
}
